#!/bin/sh

# Install deps
apk add --update git make wget

# Install rebar3
wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
mv rebar3 /usr/local/bin/rebar3

# Build release
make release
